version: '3.1'

services:

  postgres_db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=357357357
      - POSTGRES_DB=thingy-green-db

  influx_db:
    image: influxdb:latest
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=ASE
      - DOCKER_INFLUXDB_INIT_PASSWORD=123123123
      - DOCKER_INFLUXDB_INIT_ORG=ASE2023-GREEN
      - DOCKER_INFLUXDB_INIT_BUCKET=thingy
      - DOCKER_INFLUX_INIT_TOKEN=i0k66sSaxdAdIQBigftnD9dwmKoQ3kWdyRM58BVegjVTBJo4s1h8qXYxFYx3d8w3ZqTWYsov36Ytpyt89SZmMA==
    ports:
      - '8086:8086'
